const FAMILIAS = [
  { key: "vovo-rose", codigo: "ROSE2026", title: "Vovó Rose", members: ["Vovó Rose", "Vovô Zé"] },
  {key: "vovó Miria", codigo: "MIRIA2026", title: "Vovó Mira", members: ["Vovó Miria", "Esposo"] },
  { key: "elienai", codigo: "ELIENAI2026", title: "Família do Elienai", members: ["Elienai", "Isabella", "Castorina"] },
  { key: "william", codigo: "WILLIAM2026", title: "Família do William", members: ["William", "Lucas", "Pryscila"] },
  { key: "selma", codigo: "SELMA2026", title: "Família da Selma", members: ["Selma", "Matheus"] },
  { key: "rute", codigo: "RUTE2026", title: "Família da Rute", members: ["Rute", "Ronaldo", "Magno"] },
  { key: "karina", codigo: "KARINA2026", title: "Família da Karina", members: ["Karina", "Catarina", "Dário"] },
  { key: "miriam", codigo: "MIRIAM2026", title: "Família da Miriam", members: ["Miriam", "Vitória", "Carlos"] },
  { key: "moiseis", codigo: "MOISES2026", title: "Família do Moisés", members: ["Moisés", "Sandra", "Alexsander"] },
  { key: "iaia", codigo: "IAIA2026", title: "Família da Iaiá", members: ["Maria", "Limarvem", "Tio Carlinhos"] },
  { key: "olivia", codigo: "OLIVIA2026", title: "Família da Olívia", members: ["Olívia", "Daniel"] },
  { key: "ester", codigo: "ESTER2026", title: "Família da Ester", members: ["Ester", "Bebê John", "Hugo"] },
  {key: " rosana", codigo: "ROSANA2026", title:"Rosana", members: ["Rosana"] },
  { key: "bruna", codigo: "BRUNA2026", title: "Família da Bruna", members: ["Bruna", "Victor", "Sophia", "Pietro"] },
  { key: "rebeca", codigo: "REBECA2026", title: "Família da Rebeca", members: ["Rebeca", "Noah", "Lara", "Gésus"] },
  { key: "philipe", codigo: "PHILIPE2026", title: "Família do Philipe", members: ["Philipe", "Mariana", "Kaik", "Yan", "Vicente"] },
  { key: "maria-clara", codigo: "CLARA2026", title: "Família da Maria Clara", members: ["Maria Clara", "Vânia", "Adriano"] },
  { key: "maria-lucia", codigo: "LUCIA2026", title: "Família da Maria Lúcia", members: ["Maria Lúcia", "Natália", "Namorado da Natália", "Thalita"] },
  { key: "isis", codigo: "ISIS2026", title: "Família da Isis", members: ["Isis", "Sophia", "Arthur"] },
  { key: "juliana", codigo: "JULIANA2026", title: "Família da Juliana", members: ["Medina", "Júlia", "Davi", "Daniela"] },
  { key: "lili", codigo: "LILI2026", title: "Família da Lili", members: ["Lili", "Josué"] },
  { key: "lombardi", codigo: "LOMBARDI2026", title: "Família do Lombardi", members: ["Lombardi", "Edilza", "Isabela", "José Augusto"] },
  { key: "quiel", codigo: "QUIEL2026", title: "Família do Quiel", members: ["Quiel", "Lenî/neném", "Marido da Lívia", "Laís e Namorado"] },
  { key: "mariele", codigo: "MARIELE2026", title: "Família da Mariele", members: ["Mariele", "Julio Cesar"] },
  { key: "Rejane", codigo: "REJANE2026", title: "Rejane", members: ["Rejane"] },
  { key: "Poliana", codigo: "POLIANA2026", title: "Poliana", members: ["Poliana"] },
  { key: "Lucas", codigo: "LUCAS2026", title: "Lucas", members: ["Lucas","Rosana"] },
  { key: "Guilherme", codigo: "GUILHERME2026", title: "Guilherme", members: ["Guilherme","Pai do Guilherme"] },
  { key: "Igor", codigo: "IGOR2026", title: "Família do Igor", members: ["Igor","Bernardo","Alexia"] },
  { key: "Daine", codigo: "DAINE2026", title: "Família da Daine", members: ["Daine","Klear","Társila"] },
  { key: "Gabriela", codigo: "GABRIELA2026", title: "Família da Gabriela", members: ["Gabriela","Marido","Miguel","Filha"] },
  { key: "Camila", codigo: "CAMILA2026", title: "Família da Camila", members: ["Camila","Manu"] },
  { key: "Elisa", codigo: "ELISA2026", title: "Família da Elisa", members: ["Elisa","Dorisval"] },
  { key: "Sara", codigo: "SARA2026", title: "Sara", members: ["Sara"] },
  { key: "Brenda", codigo: "BRENDA2026", title: "Brenda", members: ["Brenda"] },


    
];
