const FAMILIAS = [
  { key: "vovo-rose", codigo: "ROSE2026", title: "Vovó Rose", members: ["Vovó Rose", "Vovô Zé"] },
  {key: "vovó Miria", codigo: "MIRIA2026", title: "Vovó Mira", members: ["Vovó Miria"] },
  { key: "elienai", codigo: "ELIENAI2026", title: "Família do Elienai", members: ["Elienai", "Isabella", "Castorina"] },
  { key: "william", codigo: "WILLIAM2026", title: "Família do William", members: ["William", "Lucas", "Pryscila"] },
  { key: "selma", codigo: "SELMA2026", title: "Família da Selma", members: ["Selma", "Matheus"] },
  { key: "rute", codigo: "RUTE2026", title: "Família da Rute", members: ["Rute", "Ronaldo", "Magno"] },
  { key: "karina", codigo: "KARINA2026", title: "Família da Karina", members: ["Karina", "Catarina", "Dário"] },
  { key: "miriam", codigo: "MIRIAM2026", title: "Família da Miriam", members: ["Miriam", "Vitória", "Carlos"] },
  { key: "moiseis", codigo: "MOISES2026", title: "Família do Moisés", members: ["Moisés", "Sandra", "Alexsander"] },
  { key: "iaia", codigo: "IAIA2026", title: "Família da Iaiá", members: ["Maria", "Limarvem", "Tio Carlinhos"] },
  { key: "olivia", codigo: "OLIVIA2026", title: "Família da Olívia", members: ["Olívia", "Daniel"] },
  { key: "ester", codigo: "ESTER2026", title: "Família da Ester", members: ["Ester", "Bebê John", "Hugo"] },
  {key: " rosana", codigo: "ROSANA2026", title:"Rosana", members: ["Rosana"] },
  { key: "bruna", codigo: "BRUNA2026", title: "Família da Bruna", members: ["Bruna", "Victor", "Sophia", "Pietro"] },
  { key: "rebeca", codigo: "REBECA2026", title: "Família da Rebeca", members: ["Rebeca", "Noah", "Lara", "Gésus"] },
  { key: "philipe", codigo: "PHILIPE2026", title: "Família do Philipe", members: ["Philipe", "Mariana", "Kaik", "Yan", "Vicente"] },
  { key: "maria-clara", codigo: "CLARA2026", title: "Família da Maria Clara", members: ["Maria Clara", "Vânia", "Adriano"] },
  { key: "maria-lucia", codigo: "LUCIA2026", title: "Família da Maria Lúcia", members: ["Maria Lúcia", "Natália", "Namorado da Natália", "Thalita"] },
  { key: "isis", codigo: "ISIS2026", title: "Família da Isis", members: ["Isis", "Sophia", "Arthur"] },
  { key: "juliana", codigo: "JULIANA2026", title: "Família da Juliana", members: ["Medina", "Júlia", "Davi", "Daniela"] },
  { key: "lili", codigo: "LILI2026", title: "Família da Lili", members: ["Lili", "Josué", "Poliana", "Rejane"] },
  { key: "lombardi", codigo: "LOMBARDI2026", title: "Família do Lombardi", members: ["Lombardi", "Edilza", "Isabela e Namorado", "José Augusto"] },
  { key: "quiel", codigo: "QUIEL2026", title: "Família do Quiel", members: ["Quiel", "Lenî/neném", "Marido da Lívia", "Laís e Namorado"] },
  { key: "mariele", codigo: "MARIELE2026", title: "Família da Mariele", members: ["Mariele", "Julio Cesar"] },
];
